In [30]:
import pandas as pd
import numpy as np

In [31]:
from google.colab import files
uploaded = files.upload()

df = pd.read_excel('online_retail_with_reg_.xlsx')

Saving online_retail_with_reg_.xlsx to online_retail_with_reg_ (3).xlsx

In [32]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
 8   Region       541909 non-null  object
 9   Categoria    541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 41.3+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [33]:
#Limpieza

# Eliminar nulos clave
df=df[df['CustomerID'].notna()]

# Eliminar precios inválidos
df=df[df['UnitPrice']> 0]

# Separar devoluciones
df_returns = df[df['Quantity']< 0]
df = df[df['Quantity'] > 0]

df = df.copy()

In [34]:
#Renombrar columnas
df.rename(columns={
    'InvoiceNo': 'Invoice_ID',
    'StockCode': 'Product_ID',
    'CustomerID': 'Customer_ID'
}, inplace=True)

#Ajustar tipo de dato
df['Customer_ID'] = df['Customer_ID'].astype(int)

#Crear métricas
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [35]:
#Tiempo
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['Quarter'] = df['InvoiceDate'].dt.to_period('Q').astype(str)

In [36]:
#Ordenar columnas
df = df[[
    'Invoice_ID',
    'Product_ID',
    'Description',
    'Quantity',
    'UnitPrice',
    'Revenue',
    'Customer_ID',
    'Country',
    'Region',
    'Categoria',
    'InvoiceDate',
    'Year',
    'Month',
    'Quarter'
]]

In [37]:
df.to_csv('online_retail_clean.csv', index=False)

In [38]:
df.shape
df.head()

,Invoice_ID,Product_ID,Description,Quantity,UnitPrice,Revenue,Customer_ID,Country,Region,Categoria,InvoiceDate,Year,Month,Quarter
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,15.30,17850,United Kingdom,Europe,Iluminación,2010-12-01 08:26:00,2010,12,2010Q4
1,536365,71053,WHITE METAL LANTERN,6,3.39,20.34,17850,United Kingdom,Europe,Decoración del hogar,2010-12-01 08:26:00,2010,12,2010Q4
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,22.00,17850,United Kingdom,Europe,Cocina y vajilla,2010-12-01 08:26:00,2010,12,2010Q4
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,20.34,17850,United Kingdom,Europe,Otros,2010-12-01 08:26:00,2010,12,2010Q4
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,20.34,17850,United Kingdom,Europe,Otros,2010-12-01 08:26:00,2010,12,2010Q4

In [39]:
from google.colab import files
files.download('online_retail_clean.csv')